mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: io.github.jjyy.domain
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
  type-handlers-package: io.github.jjyy.typehandler

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:3307/geekbang
    username: jy
    password: 123456
