spring:
  application:
    name: lmax-chn
  datasource:
    url: jdbc:postgresql:geekbang_0
    username: jy
    password: 123456
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: io.github.jjyy.domain
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
  type-handlers-package: io.github.jjyy.typehandler
logging:
  level:
    io.github.jjyy.mapper: debug
hmily:
  support:
    rpc:
      annotation: true
dubbo:
  consumer:
    timeout: 10000000
