spring:
  application:
    name: lmax-cn
  datasource:
    url: jdbc:postgresql:geekbang_1
    username: jy
    password: 123456
mybatis-plus:
  global-config:
    banner: false
  type-aliases-package: io.github.jjyy.domain
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath*:/mappers/*.xml
  type-handlers-package: io.github.jjyy.typehandler
dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    address: N/A
  scan:
    base-packages: io.github.jjyy.service
server:
  port: 8000
logging:
  level:
    io.github.jjyy.mapper: debug
